# Generated by Django 6.0.6 on 2026-08-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_chef',
            field=models.CharField(blank=True, choices=[('Chef Alex Salal', 'Chef Alex Salal'), ('Chef Marcus Vance', 'Chef Marcus Vance'), ('Chef Elena Rostova', 'Chef Elena Rostova'), ('Chef David Chen', 'Chef David Chen')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved')], default='New', max_length=20),
        ),
    ]
