# Generated by Django 5.2.6 on 2025-09-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
