# Generated by Django 6.0.6 on 2026-08-31 13:09

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salal', '0003_user_last_seen_alter_booking_time'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('User', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
