# Generated by Django 5.2.6 on 2025-09-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salal', '0003_accountplan_messages_project'),
    ]

    operations = []
