# Generated by Django 6.0.6 on 2026-08-31 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salal', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
