# Generated by Django 5.2.6 on 2025-09-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salal', '0002_delete_user'),
        ('salal', '0004_delete_messages'),
    ]

    operations = [
    ]
