# Generated by Django 5.2.6 on 2025-09-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salal', '0008_remove_project_client_remove_booking_status_and_more'),
    ]

    operations = []
