# Generated by Django 5.2.6 on 2025-09-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salal', '0009_remove_project_client_delete_consultation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sender',
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='plan_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', max_length=20),
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
