# Generated by Django 5.2.6 on 2025-09-26 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salal', '0010_remove_messages_recipient_remove_messages_sender_and_more'),
    ]

    operations = [
    ]
